# Generated by Django 4.1.5 on 2023-10-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestServicedesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('plumber', 'Plumber'), ('structures', 'Structures'), ('locksmith', 'Locksmith')], default='electricity', max_length=20),
        ),
    ]
