# Generated by Django 4.1.5 on 2023-10-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestServicedesk', '0002_ticket_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='apartment',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
