# Generated by Django 4.1.5 on 2023-10-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestServicedesk', '0004_ticket_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('assigned', 'Assigned'), ('solved', 'Solved')], default='reported', max_length=20),
        ),
    ]
