# Generated by Django 4.1.5 on 2023-10-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestServicedesk', '0005_ticket_comments_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='ticket_pictures/'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='comments',
            field=models.TextField(default='No comments yet'),
        ),
    ]
