# Generated by Django 4.1.5 on 2023-10-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestServicedesk', '0006_ticket_picture_alter_ticket_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='contact',
            field=models.CharField(default='Has not been provided', max_length=12),
        ),
    ]
